var mainUI ={
		slide : ()=>{return '<div class="header-btn-wrap">'
			+'    <button type="button" class="btn_menu_all"><i class="fa fa-bars"></i>전체메뉴</button>'
			+'    <div class="btn_social">'
			+'      <a class="film_society" href="/?menuId=specialcontent-filmHome&majorCode=06&minorCode=0601" title="필름 소사이어티 바로가기">필름 소사이어티</a>'
			+'      <i class="split"></i>'
			+'      <a class="classic_society" href="/?menuId=specialcontent-classicHome&majorCode=02&minorCode=0208" title="클래식 소사이어티 바로가기">클래식 소사이어티</a>'
			+'    </div>'
			+'    <div class="btn_theater">'
			+'      <span class="membership_link">'
			+'        <a class="membership_txt" href="/?menuId=center" title="고객센터 바로가기">고객센터</a>'
			+'        <i class="split"></i>'
			+'        <a class="membership_txt" href="/?menuId=membership" title="멤버십 바로가기">멤버십</a>'
			+'        <i class="split"></i>'
			+'        <a class="membership_txt" href="/?menuId=membership#menu4" title="VIP 바로가기">VIP</a>'
			+'      </span>'
			+'      <!-- 배경이 투명한 경우 상영시간표 버튼에 class=transparent -->'
			+'      <button type="button" class="img_btn header btn_time  transparent " onclick="showMenu('+'timetable-movie'+')">상영시간표</button>'
			+'      <button type="button" class="img_btn header btn_reservation focus_modal" data-toggle="modal" data-target="#myModal">빠른예매</button>'
			+'    </div>'
			+'  </div>'
			+'<div id="main" class="main-content">'
			+'<div id="container" class="main_container">'
			+'  <!-- 메인 비주얼 // -->'
			+'  <div class="section no1">'
			+'    <div class="sm_mv">'
			+'        <div class="autoOff">'
			+'          <a class="stop" href="javascript:void(0);" title="메인비주얼 정지">메인비주얼 정지</a>'
			+'        </div>'
			+'        <div class="prevNext" style="display:none;">'
			+'            <a class="prev" href="javascript:void(0);"  title="이전 메인 비주얼 보기">이전 메인 비주얼</a>'
			+'            <a class="next" href="javascript:void(0);"  title="다음 메인 비주얼 보기">다음 메인 비주얼</a>'
			+'        </div>'
			+'        <dl class="sm_mv_slide">'
			+'        <dt>'
			+'                <a href="javascript:void(0);" title="메인비주얼 1 보기">메인비주얼 1</a>'
			+'            </dt>'
			+'            <dd class="mySlides">'
			+'                <a class="sm_mv_detail" title="">'
			+'                    <span class="sm_mv_text">'
			+'                        <strong>범죄도시<em>THE OUTLAWS</em></strong>'
			+'                        <span>오늘밤, 싹 쓸어버린다!</span>'
			+'                    </span>'
			+'                </a>'
			+'                <div class="vd_playStop" style="display:none">'
			+'                    <a href="javascript:void(0);" class="vd_play" title="비디오재생">비디오재생</a>'
			+'                </div>'
			+'                <!-- Video -->'
			+'                <div class="sm_mv_bg" style="background-image: url(http://image2.megabox.co.kr/mop/home/ad/1600x600/170919_city_1600x600.jpg);">'
			+'                    <span class="blind">범죄도시</span>'
			+'                    <figure class="mv_view">'
			+'                      <div class="mv_full">'
			+'                          <video width="100%" height="100%" poster="http://image2.megabox.co.kr/mop/home/ad/1600x600/170919_city_1600x600.jpg" preload="none">'
			+'                              <source src="http://m.mvod.megabox.co.kr/encodeFile/3550/2017/09/19/b0b913cd6a2d6c906400520763e71be9_I.mp4" type="video/mp4" />'
			+'                          </video>'
			+'                      </div>'
			+'                        <figcaption class="mv_caption mvcap1">'
			+'                        <a href="javascript:void(0);" class="subscript_open" title="자막보기">자막열기</a>'
			+'                <p tabindex="0" style="display:none">'
			+'                범죄도시 30초 영상 스크립트 가이드 <br><br><br>제      공   ㈜키위미디어그룹 ㈜벤티지이앤엠 <br>배      급   메가박스㈜플러스엠 ㈜키위미디어그룹<br>제      작   ㈜홍필름 ㈜비에이엔터테인먼트<br><br>마석도 형사: 와 깡패다<br><br>[주먹 하나로 살아온]<br><br>[괴물 형사]<br><br>V.O: 이름이 장첸이라고<br><br>V.O: 독사를 죽이고 조직을 통째로 먹었답니다<br><br>[대한민국을 뒤흔든]<br><br>장첸: 내 돈은 누가 갚을래?<br><br>[신흥범죄조직]<br><br>마석도 형사: 준비해<br><br>장첸: 도끼 꺼내라<br><br>[나쁜놈들 때려잡는]<br><br>마석도 형사: 왜 같은 동포들끼리 못 잡아먹어서 안달이야, 이 자식들아<br><br>[통쾌한 범죄소탕작전]<br><br>장첸: 누가 시켰니?<br><br>장첸: 누구야!<br><br>[오늘, 싹 쓸어버린다!]<br><br>[마동석]<br><br>[윤계상]<br><br>마석도 형사: 장첸 +어디있어!<br><br>[실화 범죄 액션]<br>[범죄도시]<br><br>[10월 대개봉!]<br><br>등급) 영상물등급위원회 등급분류진행중'
			+'                </p>'
			+'                        </figcaption>'
			+'                    </figure>'
			+'                </div>'
			+'            </dd>    '
			+'        <dt>'
			+'        <a href="javascript:void(0);" title="메인비주얼 2 보기">메인비주얼 2</a>'
			+'            </dt>'
			+'            <dd class="mySlides">'
			+'                <a class="sm_mv_detail" title="">             '
			+'                    <span class="sm_mv_text">'
			+'                        <strong>[스크린뮤지엄] 정원을 그리다 : 모네에서 마티스까지<em>Painting the Modern Garden : Monet to Matisse</em></strong>'
			+'                        <span>화가의 정원으로 놀러 오세요<br>10월 26일 개봉</span>'
			+'                    </span>                '
			+'                </a>'
			+'                <div class="vd_playStop" style="display:none">'
			+'                    <a href="javascript:void(0);" class="vd_play" title="비디오재생">비디오재생</a>'
			+'                </div>'
			+'                <!-- Video -->'
			+'                <div class="sm_mv_bg" style="background-image: url(http://image2.megabox.co.kr/mop/home/ad/1600x600/171013_garden_1600x600.jpg);">'
			+'                    <span class="blind">[스크린뮤지엄] 정원을 그리다 : 모네에서 마티스까지</span>'
			+'                    <figure class="mv_view">'
			+'                      <div class="mv_full">'
			+'                          <video width="100%" height="100%" poster="http://image2.megabox.co.kr/mop/home/ad/1600x600/171013_garden_1600x600.jpg" preload="none">'
			+'                              <source src="" type="video/mp4" />'
			+'                          </video>'
			+'                      </div>'
			+'                        <figcaption class="mv_caption mvcap2">'
			+'                        <a href="javascript:void(0);" class="subscript_open" title="자막보기">자막열기</a>'
			+'                <p tabindex="0" style="display:none">               '
			+'                </p>'
			+'                        </figcaption>'
			+'                    </figure>'
			+'                </div>'
			+'            </dd>     '
			+'        <dt>'
			+'                <a href="javascript:void(0);" title="메인비주얼 3 보기">메인비주얼 3</a>'
			+'            </dt>'
			+'            <dd class="mySlides">'
			+'                <a href="javascript:MovieDetail.showPage('+'012669'+', 0);" class="sm_mv_detail" title="">'
			+'                    <span class="sm_mv_text">'
			+'                        <strong>주키퍼스 와이프<em>The Zookeepers Wife</em></strong>'
			+'                        <span>절망 속에서 기적을 키워낸 감동 실화</span>'
			+'                    </span>                '
			+'                </a>'
			+'                <div class="vd_playStop" style="display:none">'
			+'                    <a href="javascript:void(0);" class="vd_play" title="비디오재생">비디오재생</a>'
			+'                </div>'
			+'                <!-- Video -->'
			+'                <div class="sm_mv_bg" style="background-image: url(http://image2.megabox.co.kr/mop/home/ad/1600x600/1701011_wife_1600x600.jpg);">'
			+'                    <span class="blind">주키퍼스 와이프</span>'
			+'                    <figure class="mv_view">'
			+'                      <div class="mv_full">'
			+'                          <video width="100%" height="100%" poster="http://image2.megabox.co.kr/mop/home/ad/1600x600/1701011_wife_1600x600.jpg" preload="none">'
			+'                              <source src="http://m.mvod.megabox.co.kr/encodeFile/3550/2017/10/11/e74bdee3b5934b6c90e2e864a87b1ab2_I.mp4" type="video/mp4" />'
			+'                          </video>'
			+'                      </div>'
			+'                        <figcaption class="mv_caption mvcap3">'
			+'                        <a href="javascript:void(0);" class="subscript_open" title="자막보기">자막열기</a>'
			+'                <p tabindex="0" style="display:none">'
			+'                주키퍼스 와이프 30초 예고편<br>[수입 ㈜메인타이틀픽처스 배급 ㈜영화사빅]<br>[절망 속에서 기적을 키워낸 감동 실화]<br>[그 누구보다]<br>[용감한]<br>[그 어느 때보다]<br>[절실한]<br>[용기]<br>[희생]<br>[사랑]<br>[기적]<br>안토니나 : 사람은 알 수 없어 누가 적인지 누굴 믿어야 할지<br>[제시카 차스테인 주연/제작]<br>안토니나 : 아마도 그래서 내가 동물을 사랑하는 거겠지<br>[기적을 +키워낸 여인 주키퍼스 와이프 2017.10.12 12세이상관람가]'
			+'                </p>'
			+'                        </figcaption>'
			+'                    </figure>'
			+'                </div>'
			+'            </dd>        '
			+'        <dt>'
			+'                <a href="javascript:void(0);" title="메인비주얼 4 보기">메인비주얼 4</a>'
			+'            </dt>'
			+'            <dd class="mySlides">'
			+'                <a href="javascript:EventDetail.showPage('+'5569'+', 0);" class="sm_mv_detail" title="">               '
			+'                  <span class="blind">심리학 읽는 영화관_프랭크</span>               '
			+'                </a>'
			+'                <div class="vd_playStop" style="display:none">'
			+'                    <a href="javascript:void(0);" class="vd_play" title="비디오재생">비디오재생</a>'
			+'                </div>'
			+'                <!-- Video -->'
			+'                <div class="sm_mv_bg" style="background-image: url(http://image2.megabox.co.kr/mop/home/ad/1600x600/171012_frank_1600x600.jpg);">'
			+'                    <span class="blind">심리학 읽는 영화관_프랭크</span>'
			+'                    <figure class="mv_view">'
			+'                      <div class="mv_full">'
			+'                          <video width="100%" height="100%" poster="http://image2.megabox.co.kr/mop/home/ad/1600x600/171012_frank_1600x600.jpg" preload="none">'
			+'                              <source src="" type="video/mp4" />'
			+'                          </video>'
			+'                      </div>'
			+'                        <figcaption class="mv_caption mvcap4">'
			+'                        <a href="javascript:void(0);" class="subscript_open" title="자막보기">자막열기</a>'
			+'                <p tabindex="0" style="display:none">               '
			+'                </p>'
			+'                        </figcaption>'
			+'                    </figure>'
			+'                </div>'
			+'            </dd>        '
			+'      </dl>'
			+'    </div>'
			+'  </div>'
			+'  </div>'
			+'<div class="section no2">'
			+'    <div id="flip_wrapper">'
			+'        <div class="flip_box">'
			+'            <dl>'
			+'                <dt class="flip_btn1"><a href="javascript:MainMovieList.showPage();" class="icon on" title="박스오피스 보기">박스오피스</a></dt>'
			+'                <dd id="tab1">'
			+'                  <p class="text-right"><a class="icon main_more_all" href="javascript:void(0)" title="박스오피스 전체보기">박스오피스 전체보기</a></p>'
			+'                  <div class="sm_slide">'
			+'                     <div class="slide_preNex">'
			+'                         <a class="slide_prev" href="javascript:void(0);" title="이전 목록 보기">이전 목록</a>'
			+'                         <a class="slide_next" href="javascript:void(0);" title="이전 목록 보기">다음 목록</a>'
			+'                     </div>'
			+'                     <div class="slide_box">'
			+'                        <ul id="boxul" tabindex="0" style="width: 1968px; margin-left: 0px;">'
			+'                        </ul>'
			+'                     </div>'
			+'                  </div>'
			+'                </dd>'
			+'                <dt class="flip_btn2"><a id="btn2" class="icon" title="최신개봉작 보기"></a></dt>'
			+'                    <dd id="tab2" style="display:none">'
			+'                    </dd>'
			+'                </dt>'
			+'                <dt class="flip_btn3"><a id="btn3" class="icon" title="상영예정작 보기"></a></dt>'
			+'                    <dd id="tab3" style="display:none">'
			+'                    </dd>'
			+'                </dt>'
			+'                <dt class="flip_btn4"><a id="btn4" class="icon" title="특별콘텐트 보기"></a></dt>'
			+'                    <dd id="tab4" style="display:none">'
			+'                    </dd>'
			+'                </dt>'
			+'            </dl>'
			+'        </div>'
			+'    </div>'
			+'</div>'
			+'<div class="section no3">'
			+'    <div class="content_wrap narrow" style="margin-left:15%;">'
			+'    <br><br><br><h4 class="h3">새로운 이벤트</h4>'
			+'    <br>'
			+'        <div id="mainEventNew">'
			+'            <div class="eve_box0">'
			+'                <img src="http://image2.megabox.co.kr/mop/home/ad/330x630/170511_ma_330x630.jpg" alt="메가박스 마티네데이" style="float:right; margin-right:25%;">'
			+'            </div>'
			+'            <div class="eve_box1">'
			+'                <div class="eve_autoOff">'
			+'                    <a class="eve_stop" href="" title="새로운 이벤트 롤링정지">새로운 이벤트 롤링정지</a>'
			+'                    <span class="blind eve_next"></span>'
			+'                </div>'
			+'                <dl>'
			+'                    <dt class="eve1">'
			+'                        <a href="" title="새로운 이벤트1 선택" class="">새로운 이벤트1</a>'
			+'                    </dt>'
			                    +'<dd class="eve1_dd" style="background: url(http://image2.megabox.co.kr/mop/home/main/630x315/170912_hyuga_630x315.jpg&quot;) 0px 0px no-repeat; margin-left: 630px; display: none;">'
			                        +'<a href=""  title=""><span class="blind">이벤트배너 잃어버린 휴가를 찾아서! 지금 온라인 2천원 할인쿠폰 받고 메가박스로 늦은 휴가 떠나세요! 9월13일부터 9월28일까지</span></a>'
			+'                    </dd>'
			+'                    <dt class="eve2">'
			+'                        <a href="" title="새로운 이벤트2 선택" class="">새로운 이벤트2</a>'
			+'                    </dt>'
			                    +'<dd class="eve2_dd" style="background: url(&quot;http://image2.megabox.co.kr/mop/home/main/630x315/170919_skt_630_315.jpg&quot;) 0px 0px no-repeat; margin-left: 630px; display: none;">'
			+'                        <a href=""  title=""><span class="blind">메가박스 멤버십 포인트! SKT 데이터쿠폰으로 교환하세요!</span></a>'
			+'                    </dd>'
			+'                    <dt class="eve3">'
			+'                        <a href="" title="새로운 이벤트3 선택" class="">새로운 이벤트3</a>    '
			+'                    </dt>'
			                    +'<dd class="eve3_dd" style="background: url(&quot;http://image2.megabox.co.kr/mop/home/main/630x315/170921_20th_630x315.jpg&quot;) 0px 0px no-repeat; margin-left: 630px; display: none;">'
			+'                        <a href=""  title=""><span class="blind">&lt;우리의 20세기&gt; 관람평 이벤트</span></a>'
			+'                    </dd>'
			+'                    <dt class="eve4">'
			+'                        <a href="" title="새로운 이벤트4 선택" class="on">새로운 이벤트4</a>'
			+'                    </dt>'
			                    +'<dd class="eve4_dd" style="background: url(&quot;http://image2.megabox.co.kr/mop/home/main/630x315/170915_lohen_630x315.jpg&quot;) 0px 0px no-repeat; margin-left: 0px; display: block;">'
			+'                        <a href=""  title=""><span class="blind">오페라 &lt;로엔그린&gt; 음반 증정 이벤트</span></a>'
			+'                    </dd>'
			+'                </dl>'
			+'            </div>'
			+'            <div class="eve_box2">'
			+'                <div class="eve2_left">'
			+'                    <div style="display:none;">'
			+'                        <a href="" title="">'
			+'                            <img src="http://image2.megabox.co.kr/mop/home/main/315X315/170913_dmz_315x315.jpg" alt="DMZ국제다큐영화제">'
			+'                        </a>'
			+'                    </div>'
			+'                    <div style="display:none;">'
			+'                        <a href="" title="">'
			+'                            <img src="http://image2.megabox.co.kr/mop/home/main/315X315/170922_king_315X315.jpg" alt=""/>'
			+'                        </a>    '
			+'                    </div>'
			+'                    <div style="">'
			+'                        <a href="" title="">'
			+'                            <img src="http://image2.megabox.co.kr/mop/home/main/315X315/170919_cat_315x315.jpg" alt="<고양이 케디> 관람평 이벤트">'
			+'                        </a>'
			+'                    </div>'
			+'                    <div style="display:none;">'
			+'                        <a href="" title="">'
			+'                            <img src="http://image2.megabox.co.kr/mop/home/main/315X315/170921_sofia_315x315.jpg" alt="<리틀 프린세스 소피아: 신비한 섬> 극장 개봉 이벤트">'
			+'                        </a>'
			+'                    </div>'
			+'                    <div style="display:none;">'
			+'                        <a href="" title="">'
			+'                            <img src="http://image2.megabox.co.kr/mop/home/main/315X315/170919_lego_315x315.jpg" alt="<레고 닌자고 무비> 맘스 회원 시사회 이벤트">'
			+'                        </a>'
			+'                    </div>'
			+'                    </div>'
			+'                    <div class="eve2_right">'
			+'                    <div style="">'
			+'                        <a title="">'
			+'                            <img src="http://image2.megabox.co.kr/mop/home/main/315X315/160321_store_315x315.jpg" alt="메가박스 스토어 더 즐거운 영화관람을 위해 다양한 스토어 상품과 함께하세요">'
			+'                        </a>'
			+'                    </div>'
			+'                </div>'
			+'            </div>'
			+'        </div>'
			+'    </div>'
			+'<br><br><br><br><br><br>'
			+'<div id="mainBannerParallax">'
			+'<style type="text/css">'
			+'	.parallax_btn,.parallax_btn:hover,.parallax_btn:focus,.parallax_btn:active{outline:0 !important;}'
			+'</style>'
			+'<div class="parallax_txt">'
			+'	<a class="parallax_btn" href="http://www.megabox.co.kr/?menuId=theater-detail&region=55&cinema=1572" style="position: absolute; width: 178px;height: 160px; top: -25px; left: -210px">'
			+'		<span class="blind">마곡 (9월 27일 오픈)</span>'
			+'	</a>'
			+'	<a class="parallax_btn" href="http://www.megabox.co.kr/?menuId=theater-detail&region=55&cinema=3501" style="position: absolute; width: 176px;height: 160px; top: -25px; left: 30px;">'
			+'		<span class="blind">마곡 (9월 27일 오픈)</span>'
			+'	</a>'
			+'	<img alt src="http://image2.megabox.co.kr/mop/home/ad/1600x1000/170927_hongsung_865-370.png" style="margin-top: -185px; margin-left: -432.5px;"/>'
			+'</div>'
			+'<div id="grand1" class="content_middle_banner parallax_img" data-stellar-background-ratio="0.3" style="background:url(http://image2.megabox.co.kr/mop/home/ad/1600x1000/160824_bg_img.jpg) 0px -280px / cover no-repeat; overflow: visible; background-color:black;">&nbsp;</div>'
			+'</div>'
			+'</div>'
			+'<br><br><br><br><br>'
			+'<div id="event" style="width: 65%; margin: 0 auto;">'
		      +'  <h3 style="font-size: 20px; color: #333; font-weight: 700; font-family: Nanum Gothic;">제휴 이벤트</h3><br/>'
		      +'  <div class="part_eve" style="position: relative; width: 975px;">'
		      +'     <div class="part_eve_left" style="width: 632px; height: 632px; border: 1px solid #cccccc">'
		      +'        <div style="float: left; width: 315px; height: 315px;"><img src="resources/img/main/part1.jpg"/>'
		      +'     </div>'
		      +'     <div style="float: left; width:315px; height: 315px;"><img src="resources/img/main/part2.jpg"/>'
		      +'   </div>'
		      +'   <div style="float: left; width: 315px; height: 315px;"><img src="resources/img/main/part3.jpg"/>'
		      +'  </div>'
		      +'<div style="float: left; width: 315px; height: 315px;"><img src="resources/img/main/part4.jpg"/>'
		      +' </div>'
		      +' </div>'
		      +'   <div class="part_eve_right" style="position: absolute; top: 0px; right: 0px; height: 632px;">'
		      +'       <div>'
		      +'          <iframe width="330" height="630" src="resources/img/main/part5.png" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" topmargin="0" leftmargin="0"></iframe>'
		      +'       </div>'
		      +'    </div>'
		      +' </div><br><br><br><br>'
		      +'<div class="main_bottom_bn" style="margin: 0 auto">'
			   +'<a href= title="">'
				   +'   <img src="http://image2.megabox.co.kr/mop/home/ad/970x227/20150619_skt_970x227.jpg" alt="T멤버십 할인받으면 DATA가 생기는 이상하는 할인혜택, T멤버십 데이터 플러스">'
				+'</a>'
		      +'</div><br/><br/><br/><br/><br/><br/>'
		      +'<div id="movie_detail" class="modal fade"></div>'
		    +'</div>'
		    +'</div>'
			+'</div>'
			+'</div>'
			+'<br><br><br><br><br><br>'
		}
}
var compUI ={
		footer : ()=>{
			return '<div class="footer_theater">'
			+'   <div class="wrap">'
			+'      <h4 class="mb18">메가박스 영화관 찾기</h4>'
			+'      <dl class="clearfix">'
			+'         <dt>서울</dt>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=10&amp;cinema=1372&#39;">강남</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=10&amp;cinema=1359&#39;">강남대로(씨티)</a></dd>'
			+'            <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=10&amp;cinema=1003&#39;">동대문</a></dd>'
			+'            <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=10&amp;cinema=1572&#39;">마곡</a></dd>'
			+'            <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=10&amp;cinema=1581&#39;">목동</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=10&amp;cinema=1311&#39;">상봉</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=10&amp;cinema=1371&#39;">센트럴</a></dd>'
			+'            <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=10&amp;cinema=1381&#39;">송파파크하비오</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=10&amp;cinema=1421&#39;">수유</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=10&amp;cinema=1202&#39;">신촌</a></dd>'
			+'        <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=10&amp;cinema=1221&#39;">은평</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=10&amp;cinema=1561&#39;">이수</a></+dd>'                                 
			+'            <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=10&amp;cinema=1321&#39;">창동</a></dd>'         
			+'            <dd><a +href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=10&amp;cinema=1351&#39;">코엑스</a></dd>'
			+'            <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=10&amp;cinema=1571&#39;">화곡</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=10&amp;cinema=1562&#39;">ARTNINE</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=10&amp;cinema=1002&#39;">EOE4</a></dd>'
			+'      </dl>'
			+'      <dl class="clearfix">'
			+'         <dt>경기</dt>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=35&amp;cinema=4121&#39;">고양스타필드</a></dd>'
			+'            <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=35&amp;cinema=4151&#39;">김포</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=35&amp;cinema=4721&#39;">남양주</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=35&amp;cinema=4451&#39;">동탄</a></dd>'
			+'          <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=35&amp;cinema=4804&#39;">의정부 민락</a></dd>'
			+'            <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=35&amp;cinema=4113&#39;">백석</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=35&amp;cinema=4722&#39;">별내</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=35&amp;cinema=4631&#39;">분당</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=35&amp;cinema=4411&#39;">수원</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=35&amp;cinema=4421&#39;">수원남문</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=35&amp;cinema=4291&#39;">시흥배곧</a></dd>'                                                                                                                                                                                                              
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=35&amp;cinema=4253&#39;">안산중앙</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=35&amp;cinema=4821&#39;">양주</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=35&amp;cinema=4431&#39;">영통</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=35&amp;cinema=4471&#39;">오산</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=35&amp;cinema=4111&#39;">일산</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=35&amp;cinema=4104&#39;">일산벨라시타</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=35&amp;cinema=4112&#39;">킨텍스</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=35&amp;cinema=4132&#39;">파주금촌</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=35&amp;cinema=4115&#39;">파주운정</a></+dd>'                            
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=35&amp;cinema=4131&#39;">파주출판도시</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=35&amp;cinema=4501&#39;">평택</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=35&amp;cinema=4651&#39;">하남스타필드</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=35&amp;cinema=4461&#39;">DriveM(용인)</a></dd>'
			+'      </dl>'
			+'      <dl class="clearfix">'
			+'         <dt>인천</dt>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=35&amp;cinema=4041&#39;">검단</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=35&amp;cinema=4062&#39;">송도</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=35&amp;cinema=4051&#39;">인천논현</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=35&amp;cinema=4042&#39;">청라</a></dd>'
			+'      </dl>'
			+'      <dl class="clearfix dt_st1">'
			+'         <dt>대전  |  세종  |  충청</dt>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=45&amp;cinema=3141&#39;">공주</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=45&amp;cinema=3021&#39;">대전</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=45&amp;cinema=3551&#39;">보령</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=45&amp;cinema=3391&#39;">세종</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=45&amp;cinema=3651&#39;">진천</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=45&amp;cinema=3301&#39;">천안</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=45&amp;cinema=3901&#39;">제천</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=45&amp;cinema=3801&#39;">충주</a></dd>'
			+'      </dl>'
			+'      <dl class="clearfix dt_st2">'
			+'         <dt>부산  |  경상</dt>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=55&amp;cinema=6701&#39;">거창</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=55&amp;cinema=6311&#39;">경남대</a></dd>'
			+'            <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=55&amp;cinema=7122&#39;">경산하양</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=55&amp;cinema=7801&#39;">경주</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=55&amp;cinema=7304&#39;">구미</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=55&amp;cinema=7303&#39;">구미강동</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=55&amp;cinema=7401&#39;">김천</a></dd>'
			+'            <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=55&amp;cinema=7901&#39;">남포항</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=55&amp;cinema=7022&#39;">대구(칠성로)</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=55&amp;cinema=6161&#39;">덕천</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=55&amp;cinema=7011&#39;">동대구</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=55&amp;cinema=7451&#39;">문경</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=55&amp;cinema=6001&#39;">부산극장</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=55&amp;cinema=6906&#39;">부산대</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=55&amp;cinema=7021&#39;">북대구(칠곡)</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=55&amp;cinema=6641&#39;">사천</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=55&amp;cinema=6642&#39;">삼천포</a></dd>'
			+'            <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=55&amp;cinema=6141&#39;">서면</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=55&amp;cinema=7601&#39;">안동</a></dd>'
			+'            <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=55&amp;cinema=6261&#39;">양산</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=55&amp;cinema=6811&#39;">울산</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=55&amp;cinema=6601&#39;">진주</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=55&amp;cinema=6421&#39;">창원</a></dd>'
			+'           <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=55&amp;cinema=6121&#39;">해운대(장산)</a></dd>'
			+'			</dl>'
			+'      <dl class="clearfix dt_st2">'
			+'         <dt>광주  |  전라</dt>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=65&amp;cinema=5011&#39;">광주(충장로)</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=65&amp;cinema=5021&#39;">광주상무</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=65&amp;cinema=5061&#39;">광주하남</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=65&amp;cinema=5901&#39;">남원</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=65&amp;cinema=5301&#39;">목포</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=65&amp;cinema=5302&#39;">목포하당(포르모)</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=65&amp;cinema=5612&#39;">송천</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=65&amp;cinema=5401&#39;">순천</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=65&amp;cinema=5402&#39;">신대</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=65&amp;cinema=5551&#39;">여수</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=65&amp;cinema=5001&#39;">전대(광주)</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=65&amp;cinema=5063&#39;">전주(객사)</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=65&amp;cinema=5064&#39;">첨단(광주)</a></dd>'
			+'      </dl>'
			+'      <dl class="clearfix">'
			+'         <dt>강원</dt>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=35&amp;cinema=2001&#39;">남춘천</a></dd>'
			+'            <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=70&amp;cinema=2171&#39;">속초</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=70&amp;cinema=2201&#39;">원주</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=70&amp;cinema=2202&#39;">원주센트럴</a></dd>'
			+'      </dl>'
			+'      <dl class="clearfix">'
			+'         <dt>제주</dt>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=80&amp;cinema=6901&#39;">제주</a></dd>'
			+'         <dd><a href="javascript:void(0);" onclick="parent.location.href = &#39;http://www.megabox.co.kr/?menuId=theater-detail&amp;region=80&amp;cinema=6902&#39;">제주아라</a></dd>'
			+'      </dl>'
			+'   </div>'
			+'</div>'
			   +'<footer id="footer">'
			   +'<div class="wrap">'
			   +'   <div class="logo">'
			   +'    <a href="/" title="MEGABOX 메인으로 가기"><img src="http://image2.megabox.co.kr/mop/home/logo_footer_new.png" alt="MEGABOX"></a>'
			   +' </div>'
			   +' <ul>'
			   +'    <li class="footer_company"><a href="javascript:void(0)"  title="회사소개 바로가기">회사소개</a></li>'
			   +'    <li><a href="javascript:void(0)" title="채용정보 바로가기">채용정보</a></li>'
			   +'    <li><a href="javascript:void(0)"  title="제휴/광고/부대사업 문의 바로가기">제휴/광고/부대사업 문의</a></li>'
			   +'    <li><a href="javascript:void(0)"  title="이용약관 바로가기">이용약관</a></li>'
			   +'    <li><a class="c_mintlite" href="javascript:void(0)"  title="개인정보 처리방침 바로가기">개인정보 처리방침</a></li>'
			   +'    <li><a href="javascript:void(0)" title="고객센터 바로가기">고객센터</a></li>'
			   +' </ul>'
			   +' <div class="text1">'
			   +'    서울특별시 강남구 도산대로 156, 2층 메가박스(주) (논현동, 중앙엠앤비사옥)<br />'
			   +'	  대표자명 김진선  |  개인정보보호 책임자 경영지원실 실장 이재원<br />'
			   +'     사업자등록번호 211-86-59478  |  통신판매업신고번호 제 833호'
			   +'   </div>'
			   +'  <div class="text3">Copyright 2014 by MEGABOX. All rights reserved</div>'
			   +' <div class="ft_etc">'
			   +'    <a class="apple blank" href="https://itunes.apple.com/kr/app/megabox/id894443858?l=ko&ls=1&mt=8" title="MEGABOX IOS APP 설치페이지열기" target="_blank">'
			   +'       <span class="blind">MEGABOX iPhone APP</span>'
			   +'    </a>'
			   +'    <a class="android blank" href="https://play.google.com/store/apps/details?id=com.megabox.mop" title="MEGABOX Android APP 설치페이지열기" target="_blank">'
			   +'       <span class="blind">MEGABOX Android APP</span>'
			   +'    </a>'
			   +'    <a class="instagram blank" href="http://instagram.com/megaboxon" title="MEGABOX Instagram 열기" target="_blank">'
			   +'       <span class="blind">MEGABOX Instagram</span>'
			   +'    </a>'
			   +'    <a class="facebook blank" href="https://www.facebook.com/megaboxon" title="MEGABOX Facebook 열기" target="_blank">'
			   +'       <span class="blind">MEGABOX Facebook</span>'
			   +'    </a>'
			   +'    <a class="twitter blank" href="https://twitter.com/megaboxon" title="MEGABOX Twitter 열기" target="_blank">'
			   +'       <span class="blind">MEGABOX Twitter</span>'
			   +'    </a>'
			   +'    <div class="text4 blind"><span>ARS 1544-0070</span></div>'
			   +' </div>'
			   +'</div>'
			   +'</footer>'
		},
		header : ()=>{
			return '<div class="header-wrap">'
				+'<div class="navigation">'
					+'         <div class="logo" id="top_logo">'
					+'            <a title="MEGABOX 메인으로 가기(140)"><img src="http://image2.megabox.co.kr//mop/home/logo_new.png" alt="MEGABOX" class="ie_logo big" /></a>'
					+'         </div>'
					+'         <ul id="nav_head">'
					+'            <li id="main_movie"><a class="icon i1" title="영화 바로가기">영화</a></li>'
					+'            <li><a class="icon i2 " title="큐레이션 바로가기">큐레이션</a></li>'
					+'            <li><a class="icon i3 " title="영화관메인 바로가기">영화관메인</a></li>'
					+'            <li><a class="icon i4 " title="특별관 바로가기">특별관</a></li>'
					+'            <li><a class="icon i5 " title="스토어 바로가기"><span class="i_new">new</span>스토어</a></li>'
					+'            <li><a class="icon i6 " title="이벤트 바로가기">이벤트</a></li>'
					+'         </ul>'
					+'      </div>'
					+'</div>'
		},
		boxoffice : (img)=>{ return '<li class="item" tabindex="0">'
			+'                              <div class="thumb flip" tabindex="0">'
			+'                                 <div class="upper">'
			+'                                    <span class="boxoffice n1">01</span>'
			+'                                    <img src="'+img+'" alt="범죄도시"> <!-- 포스터 -->'
			+'                                    <!-- 특별관 마크 -->'
			+'                                    <span class="mark_special_wrp">'
			+'                                    <i class="icon m2">m2</i>'
			+'                                    <i class="icon boutiquem">theBoutique</i>'
			+'                                    </span>'
			+'                                 </div>'
			+'                                 <div class="lower">'
			+'                                    <div class="back_wrap">'
			+'                                       <div name="starScore_012675" class="star-wrap" data-code="012675" style="cursor: pointer; width:180px;">'
			+'                                        <input type="image" src="http://image2.megabox.co.kr/mop/home/star_big_off.png" alt="별점1 괜히봤어요" title="별점1 괜히봤어요">'
			+'                                        <input type="image" src="http://image2.megabox.co.kr/mop/home/star_big_off.png" alt="별점2 기대하진 말아요" title="별점2 기대하진 말아요">'
			+'                                        <input type="image" src="http://image2.megabox.co.kr/mop/home/star_big_off.png" alt="별점3 무난했어요" title="별점3 무난했어요">'
			+'                                        <input type="image" src="http://image2.megabox.co.kr/mop/home/star_big_off.png" alt="별점4 기대해도 좋아요!" title="별점4 기대해도 좋아요!">'
			+'                                        <input type="image" src="http://image2.megabox.co.kr/mop/home/star_big_off.png" alt="별점5 너무 멋진 영화였어요!" title="별점5 너무 멋진 영화였어요!">'
			+'                                        <input type="hidden" name="score">'
			+'                                       </div>'
			+'                                       <p class="text" name="starScoreTxt_012675">평점을 입력해주세요</p>'
			+'                                    </div>'
			+'                                    <span class="bg"></span>'
			+'                                    <img src="'+img+'" alt="범죄도시" class="back_poster"> <!-- 포스터 -->'
			+'                                 </div>'
			+'                              </div>'
			+'                              <div class="front-info">'
			+'                                 <!-- 영화정보// -->'
			+'                                 <div class="movie_info">'
			+'                                    <h3 class="sm_film">'
			+'                                       <span class="film_rate age_19">청소년관람불가</span>'
			+'                                       <a class="film_title" title="영화상세 보기">킹스맨: 골든 서클</a>'
			+'                                    </h3>'
			+'                                    <div id="main_btn_wrap" class="btn_wrap sm_btn">'
			+'                                    </div>'
			+'                                 </div>'
			+'                                 <!-- //영화정보 -->'
			+'                              </div>'
			+'                           </li>'
		},
		loginUI : ()=>{ return '<div class="login_info remove_loginInfo" id="login_wrap">'
			+'<span class="top"></span>'
			+'<div class="middle">'
			+'<div class="login_input_wrap" id="login_id_view">'
			+'	<div class="input_wrap">'
			+'		<label for="login-id" class="login-id">아이디</label>'
			+'		<input type="text" id="login-id" name="userId" placeholder="아이디" title="아이디입력" maxlength="20" class="mb8" value="" allowtype="hangul number alphabet special" keyenter="input:submit.img_btn.user" />'
			+'		<label for="login-pw" class="login-pw">비밀번호</label>'
			+'		<input type="password" id="login-pw" name="userPw" placeholder="비밀번호" title="비밀번호입력" maxlength="20" value="" keyenter="input:submit.img_btn.user" />'
			+'		<p class="clearfix c_purple ck_popup">'
			+'			<span class="pull-left">'
			+'				<label for="keep_login" class="mr5">아이디 저장</label>'
			+'				<input type="checkbox" id="keep_login" name="keepLogin" class="style_input" title="아이디 저장"/>'
			+'				<strong class="reep_login_pop">'
			+'					<i></i>'
			+'					개인정보 보호를 위해<br/>'
			+'					개인 PC에서만 사용해 주세요.'
			+'					<a href="/?menuId=center-faq&p=&p2=로그인+상태+유지+기능+주의+사항" class="go_help" title="도움말 보기">도움말 보기</a><!-- 로그인 상태 유지 기능 주의 사항 검색 -->'
			+'					<a href="javascript:void(0)" class="img_btn pop_close" title="로그인 상태유지 도움말 팝업 닫기">로그인 상태유지 도움말 팝업 닫기</a>'
			+'				</strong>'
			+'					<div class="ad_wrap pull-right">'
			+'					<a href="javascript:adHasClick('+'https://www.sepay.org/spm/join?regSiteCode=XF&ctgCode=1&subCode=1'+', 0)" class="ad_box" title=""><img src="http://image2.megabox.co.kr/mop/home/ad/loginad/login_ad_01.png" alt="휴대폰 간편 로그인"/></a>'
			+'				</div>'			
			+'				</span>'
			+'		</p>'
			+'		<input id="main_login" type="submit" value="로그인" title="로그인" class="img_btn user" onclick="login();" />'
			+'	</div>'
			+'</div>'
			+'</div>'
			+'<div class="join_btn">'
			+'<ul>'
			+'	<li class="col1"></li>'
			+'	<li class="col2"><a title="비회원 예매확인/취소 바로가기">비회원 예매확인/취소</a></li>'
			+'	<li class="col3"><a href="javascript:void(0)" title="ID/PW찾기">ID/PW찾기</a></li>'
			+'	<li class="col4"><a href="javascript:void(0)" title="회원가입">회원가입</a></li>'
			+'	<li class="col5"><a href="javascript:void(0)" title="휴면계정 복구신청">휴면계정 복구신청</a></li>'
			+'	<li class="col6"></li>'
			+'</ul>'
			+'</div>'
			+'<div class="ad_wrapper">'
			+'<script type="text/javascript" src="http://mlink-vad.netinsight.co.kr/NetInsight/js/megabox/login/login@bottom"></script>'
			+'</div>'
			+'<a href="javascript:void(0);" id="exit" class="login_box_close" title="닫기">닫기</a>'
			+'</div>'
		},
		afterlogin : ()=>{return '<div class="member_info remove_loginInfo" style="cursor: pointer;">'
			+'<div class="photo">'
			+'<img src="http://image2.megabox.co.kr/mop/home/user/bg_myphoto.png" alt="프로필 사진 배경이미지" style="position: absolute;left: 0;top: 0;">'
			+'<img src="http://image2.megabox.co.kr/mop/home/user/profile_m.png" alt="프로필 사진" id="topMyphotoImage">'
			+'<!-- 멤버등급 아이콘 -->'
			+'<i class="icon member_icon normal">일반</i>'
		+'</div>'
		+'<div class="name">'
			+'<a class="name_btn" title="회원정보 간략보기">'
				+'<strong>유주열<span>님</span></strong>'
				+'<span id="login_drop" class="name_arrow"><i class="fa fa-chevron-down"></i></span>'
			+'</a>'
//			+'<a href="javascript:void(0);" class="name_membership c_mint" onclick="showMenu('mypage-booking')" title="예매내역 바로가기">예매확인/취소</a>'
			+'<a href="javascript:void(0);" id="name_membership_c_mint" class="name_membership c_mint" onclick="showMenu()" title="예매내역 바로가기">예매확인/취소</a>'
		+'</div>'
	+'</div>'
	}
}